#配置service
server:
  port: 8081
  servlet:
    session:
      timeout: 30m  #session过期时间
  tomcat:
    uri-encoding: utf-8  #编码格式
#配置spring
spring:
  thymeleaf:
    cache: false  #配置thymeleaf
    prefix: classpath:/templates/
    suffix: .html
    #encoding: UTF-8
    servlet:
      content-type: text/html
    mode: HTML
  application:  #应用
    name: addressbook  #名称
  jpa:
    open-in-view: false
  datasource:   #数据源     数据库相关配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/address?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useAffectedRows=true&serverTimezone=Asia/Shanghai
    username: root
    password: wt12138..
    dbcp2:
      max-idle: 10  #最大连接
      max-wait-millis: 10000
      min-idle: 5
      initial-size: 5
  http:
    encoding:
      force: true
  resources:
        static-locations: classpath:/     #默认是static下  不配置，资源前不用加static，配置 是拦截器 不拦截 静态文件。否则在static下自建一个文件夹。进行配置拦截
  redis:
    host: 127.0.0.1   #redis服务器地址
    port: 6379    #Redis链接端口
    database: 0   #redis数据库索引
    jedis:
      pool:
        max-active: 8         #链接数
        max-wait: 5000       #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8         #最大空闲链接
        min-idle: 5         #最小空闲链接
    timeout: 5000           #链接超时时间
logging:
  level:
    ROOT: WARN
    com.yale: DEBUG
  file:
    name: target/app.log

#mybaitis
mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.homework.addressbook
  configuration:
    map-underscore-to-camel-case: true    #驼峰转换



